notify_email:
  name: Notify Email
  type: string
  default: mreider@engineyard.com

log_out_sso:
  name: Log user out of SSO on logout?
  type: boolean
  default: no

accept_applications:
  name: Accepting Application
  type: boolean
  default: true

conversion_rate:
  name: Conversion Rate
  type: decimal
  default: 1.0

important_number:
  name: Important Number
  type: integer
  default: 1

long_list:
  name: Long List
  type: list
  default:
    - [ One, 1 ]
    - [ Two, 2 ]
    - [ Three, 3 ]
